name: Tests

on:
  push:
    branches:
      - main

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install protostar
        run: |
          curl -L https://raw.githubusercontent.com/software-mansion/protostar/master/install.sh | bash -s -- -v 0.3.2
      - name: Update env variables
        run: |
          source /home/runner/.bashrc | bash
      - name: Install protostar dependencies
        run: /home/runner/.protostar/dist/protostar/protostar install
      - name: Run protostar tests
        run: /home/runner/.protostar/dist/protostar/protostar test src
